on: 
  pull_request:
    paths:
    - 'vishaalpal/*'

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment on all PRs targeting vishaalpal/*
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: 'Well done ${{ secrets.VISHAALPAL_NAME }} ! This is a nice PR.'
          GITHUB_TOKEN: ${{ secrets.VISHAALPAL_GH_PAT }} 
