on: 
  pull_request:
    paths:
    - 'ravisenevirathne/*'

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: 'Well done ${{ secrets.RAVISENEVIRATHNE_NAME }} ! This is a nice PR.'
          GITHUB_TOKEN: ${{ secrets.RAVISENEVIRATHNE_GH_TOKEN }} 