on: 
  pull_request:
    paths:
    - 'beardedsamwise/c05-actions-02/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Push image to Docker Hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Build and push image to Docker Hub
        run: make all
        env:
          BEARDED_DOCKER: ${{ secrets.BEARDED_DOCKER }}
      
