on: 
  pull_request:
    paths:
    - 'beardedsamwise/*'
  
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment on all PRs raised by beardedsamwise
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Well done ${{ secrets.BEARDED_NAME }} ! This is a nice PR.'
          GITHUB_TOKEN: ${{ secrets.BEARDED_KEY }}
