name: Pull Request Comment
on:
    pull_request:
        types: [opened]
        paths: 'gepifanio/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps: 
    - name: comment on PR gepifanio
      uses: actions/github-script@v1
      with:
        GITHUB_TOKEN: '${{ secrets.GEPIFANIO_TOKEN }}'
        script: |
          var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
          var PR_HEAD_SHA = process.env.PR_HEAD_SHA;
          github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Well done ${PR_HEAD_USERREPO}/${PR_HEAD_SHA} ! This is a nice PR`
          })
      env:
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}
