name: gepifanio
on:
    pull_request:
        types: [opened]
        paths: 'gepifanio/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
    
      - name: Has Changed Path
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-docker
        with:
          paths: gepifanio/c05-actions02

      - name: Get outputs
        if: steps.changed-docker.outputs.changed == 'true'
        working-directory: 'gepifanio/c05-actions02'
        id: vars
        shell: bash
        run: make github_variables

      - name: build and publish docker image
        if: steps.changed-docker.outputs.changed == 'true'
        run: make all
        working-directory: 'gepifanio/c05-actions02'
        env:
          GEPIFANIO_DOCKER_ACCESS_TOKEN: ${{ secrets.GEPIFANIO_DOCKER_ACCESS_TOKEN }}

      - name: comment image pushed
        if: steps.changed-docker.outputs.changed == 'true'
        uses: nickatnight/add-pr-comment-action@v1    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Well done image **${{ steps.vars.outputs.image_name }}**"
          allow_duplicates: false

      - name: comment user name
        uses: nickatnight/add-pr-comment-action@v1    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Well done **${{ secrets.GEPIFANIO_USER_NAME_TOKEN }}**! This is a nice PR"
          allow_duplicates: false