name: GPAVELAR/C05-ACTIONS02
on:
  pull_request:
    branches:
    - master
    paths: 'gpavelar/c05-actions02/**'

defaults:
  run:
    working-directory: 'gpavelar/c05-actions02'

jobs:
  comment:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker build and tag
      run: |
        make docker-build
        echo ${SHORT_SHA}
        echo ${IMAGE}
      shell: bash

    - name: Docker Push Image
      env:
        GPAVELAR_DH_TOKEN: ${{ secrets.GPAVELAR_DH_TOKEN }}
      run: make docker-push

    - name: Comment Image and Short SHA
      uses: mshick/add-pr-comment@v1
      env: 
        IMAGE: "action02"
        SHORT_SHA: "v1"
      with:
        message: "${{ env.IMAGE }}:${{ env.SHORT_SHA }}"
        repo-token: ${{ secrets.GPAVELAR_PAT }}
        allow-repeats: true 

    - name: Comment
      uses: mshick/add-pr-comment@v1
      with:
        message: "Well done ${{ secrets.GPAVELAR_USERNAME }} ! This is a nice PR"
        repo-token-user-login: 'github-actions[bot]'
        repo-token: ${{ secrets.GPAVELAR_PAT }}
        allow-repeats: false 