name: GPAVELAR/C05-ACTIONS01
on:
  pull_request:
    branches:
    - master
    paths: 'gpavelar/**'

jobs:
  comment:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MY_NAME: ${{ secrets.GPAVELAR_USERNAME }}

    steps:
    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GPAVELAR_PAT }}
      with:
        message: "Well done ${{ env.MY_NAME }}! This is a nice PR"
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: false