name: mail2kvanitha-c05-actions01

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Well done ${{ secrets.VANI_NAME }}! This is a nice PRN
          repo-token: ${{ secrets.VANI_TOKEN }}
          allow-repeats: false
