# This is a basic workflow to help you get started with Actions

name: mail2kvanitha-c05-actions01

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    paths:
      - "mail2kvanitha/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.VANI_TOKEN }}
      with:
        message: |
          WELL DONE ${{ SECRETS.VANI_NAME }}! This is a nice PRN
        allow-repeats: false
