name: mail2kvanitha-c05-actions01

on:
  pull_request:
    paths:
      - "mail2kvanitha/**"

jobs:
  Comment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.VANI_TOKEN }}
      with:
        message: |
          WELL DONE ${{ SECRETS.VANI_NAME }}! This is a nice PRN
        allow-repeats: false
