# This is a basic workflow to help you get started with Actions

name: mail2kvanitha-c05-actions02

on:
  pull_request:
    paths:
      - "mail2kvanitha/c05-actions02/**"

jobs:
  c05-actions02:
    runs-on: ubuntu-latest
    name: Docker image push to DockerHub
    steps:
      - name: GH Checkout
        uses: actions/checkout@v2
        
      - name: Docker Image build and push
        run: |
          cd mail2kvanitha/c05-actions02
          echo "##[set-output name=get_sha;]$(git rev-parse --short HEAD)"
          make build
          DOCKER_PASS=${{ secrets.VANI_DOCKER_PASS }} make push
        id: getsha
        
      - name: C05-actions02 PR Comment
        # https://github.com/marketplace/actions/add-pr-comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Well done ${{ secrets.VANI_NAME }}! Image pushed with tag ${{ steps.getsha.outputs.get_sha }}
          repo-token: ${{ secrets.VANI_TOKEN }}
          allow-repeats: false     
