name: mail2kvanitha-c05-actions01

on:
  pull_request:
    paths:
      - "mail2kvanitha/c05-actions01/**"

jobs:
  c05-actions01:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Well done ${{ secrets.VANI_NAME }}! This is a nice PRN
          repo-token: ${{ secrets.VANI_TOKEN }}
          allow-repeats: false
