on: 
  pull_request:
    paths:
    - 'marshalldaniel/*'
  
jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment on all PRs targeting marshalldaniel/*
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Well done ${{ secrets.MARSHALLDANIEL_NAME }} ! This is a nice PR.'
          GITHUB_TOKEN: ${{ secrets.MARSHALLDANIEL_GHKEY }}