name: comment-on-pr

on:
  pull_request:
    paths:
      - 'mrcsmonteiro/**'

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          message: 'Well done ${{ secrets.MY_NAME }} ! This is a nice PR'
