name: Raghu Github Actions C05-01
on:
  pull_request:
        paths:
            - "raghunadhpokkalath/**"
jobs:
    prcomment:
        runs-on: ubuntu-latest
        steps:
            - uses: github-actions-up-and-running/pr-comment@v1.0.0
              with:
                repo-token: ${{ secrets.RAGHU_PAT }}
                message: Well done ${{ secrets.RAGHU_NAME }}! This is a nice PRN
